version: '3.7'

services:

  catering-app:
    container_name: tms-application
    image: denisliubenkov/tms:v1
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TaskManagementSystem
    image: postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge

